"""General context: background information given to the reviewer for every proposal, in all subject areas.

Stored as <skills_dir>/CONTEXT.md. It is either written by hand / PUT over the API, or generated by
the AI from an admin prompt (e.g. "summarise the technologies listed on https://..."). Optional YAML
front matter records how it was generated (prompt, model, generated_at).
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import yaml
from pydantic import BaseModel

from .prompt import CONTEXT_SYSTEM_PROMPT
from .providers import AIError, Provider
from .skills import _FRONT_MATTER_RE

CONTEXT_FILE = "CONTEXT.md"


class Context(BaseModel):
    content: str
    # Set when the context was generated by the AI
    prompt: str | None = None
    model: str | None = None
    generated_at: datetime | None = None


class ContextStore:
    """Reads the context from disk on every call, so edits apply without a restart."""

    def __init__(self, skills_dir: Path):
        self.path = skills_dir / CONTEXT_FILE

    def load(self) -> Context | None:
        if not self.path.is_file():
            return None
        text = self.path.read_text(encoding="utf-8")
        match = _FRONT_MATTER_RE.match(text)
        meta, body = ({}, text)
        if match:
            loaded = yaml.safe_load(match.group(1))
            if isinstance(loaded, dict):
                meta, body = loaded, match.group(2)
        if not body.strip():
            return None
        return Context(
            content=body.strip(),
            prompt=meta.get("prompt"),
            model=meta.get("model"),
            generated_at=meta.get("generated_at"),
        )

    def save(self, context: Context) -> Context:
        meta = context.model_dump(exclude={"content"}, exclude_none=True, mode="json")
        front = f"---\n{yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)}---\n\n" if meta else ""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(f"{front}{context.content.strip()}\n", encoding="utf-8")
        return context

    def delete(self) -> bool:
        if not self.path.is_file():
            return False
        self.path.unlink()
        return True


async def generate_context(prompt: str, provider: Provider) -> tuple[Context, dict]:
    """Let the AI write the context from the admin's prompt. Returns the context and token usage."""
    answer = await provider.generate(CONTEXT_SYSTEM_PROMPT, prompt)
    if not answer.text.strip():
        raise AIError("The AI agent returned an empty context")
    context = Context(
        content=answer.text.strip(),
        prompt=prompt,
        model=answer.model,
        generated_at=datetime.now(timezone.utc).replace(microsecond=0),
    )
    return context, answer.usage
